### PR TITLE
Fix bugs and codesmells

### LINKED ISSUE #208: Fix bugs and code smells in overworld backend
## Current Behavior
The overworld backend has bugs and code smells.

## Expected Behavior
The overworld backend has no bugs and code smells.

## DoD
- [x] Known bugs in the overworld backend are fixed.
- [x] code smells are fixed.

### PR DESCRIPTION
**Pull request by Aaron2000119**
Closes https://github.com/Gamify-IT/issues/issues/208.
fix code smells and various small bugs.
Also added that the npc.completed gets resetted, if the npc is updated.
The error if you send putMinigameTask and inputMinigameStatistic at the same time is adressed with new implementation which is approximatly 20 times faster.

### CODE REVIEW

File: src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java [hunk 1]
```diff
@@ -24,7 +25,7 @@ public class PlayerTaskStatisticData {
 
   @Min(0)
   @Max(100)
-  long score;
+  int score;
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java]: Why this change?

File: src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java [hunk 2]
```diff
@@ -92,6 +98,9 @@ public NPC getNPCFromDungeon(final int courseId, final int worldIndex, final int
    * @return the npc area as DTO
    */
   public NPCDTO updateNPCFromWorld(final int courseId, final int worldIndex, final int npcIndex, final NPCDTO npcDTO) {
+    List<PlayerNPCStatistic> statistics = playerNPCStatisticRepository.findByNpcId(npcDTO.getId());
+    List<PlayerNPCStatistic> courseStatistics = playerNPCStatisticRepository.findByCourseId(courseId);
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java]: courseStatistics unused?

File: src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java [hunk 3]
```diff
@@ -92,6 +98,9 @@ public NPC getNPCFromDungeon(final int courseId, final int worldIndex, final int
...
+    statistics.forEach(statistic -> statistic.setCompleted(false));
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java]: statistics does not get saved?

File: src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java [hunk 4]
```diff
@@ -118,6 +127,9 @@ public NPCDTO updateNPCFromDungeon(
     final int npcIndex,
     final NPCDTO npcDTO
   ) {
+    List<PlayerNPCStatistic> statistics = playerNPCStatisticRepository.findByNpcId(npcDTO.getId());
+    statistics.forEach(statistic -> statistic.setCompleted(false));
+    playerNPCStatisticRepository.saveAll(statistics);
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java]: I write this here also for the code snippet above: It should be better we write a update query instead of getting all statistics, change the value and save then all objects.

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java [hunk 5]
```diff
@@ -134,30 +140,27 @@ public PlayerTaskStatisticDTO submitData(final PlayerTaskStatisticData data) {
     );
   }
 
-  private void calculateCompletedDungeons(final PlayerStatistic playerstatistic) {
+  private void isDungeonCompleted(Dungeon dungeon, PlayerStatistic playerStatistic) {
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]: the name implicates that the return value is a boolean (and typically no logic stuff is made, at least no update queries). So I recommend renaming the function and maybe return a boolean.

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java [hunk 6]
```diff
@@ -134,30 +140,27 @@ public PlayerTaskStatisticDTO submitData(final PlayerTaskStatisticData data) {
...
+      .getMinigameTasks()
+      .parallelStream()
+      .allMatch(minigameTask ->
+        playerTaskStatistics
+          .parallelStream()
+          .filter(playerTaskStatistic -> playerTaskStatistic.getMinigameTask().equals(minigameTask))
+          .anyMatch(PlayerTaskStatistic::isCompleted)
+      );
+    long duration = System.nanoTime() - currentTime;
+    System.out.println(duration);
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]: Maybe annotate the class with `@Slf4j` and use log.debug(). Is this logging needed in the future?

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java [hunk 7]
```diff
@@ -134,30 +140,27 @@ public PlayerTaskStatisticDTO submitData(final PlayerTaskStatisticData data) {
...
+    if (dungeonCompleted) {
+      List<Area> completedDungeons = playerStatistic.getCompletedDungeons();
+      completedDungeons.add(dungeon);
+      playerStatistic.setCompletedDungeons(completedDungeons);
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]: Is this really needed?

**Review by maexled — CHANGES_REQUESTED** [review]
I noticed we should maybe make a general function for updating an NPC in an area instead of two separate functions for updating an NPC in a world and updating in a dungeon where you have to update 2 functions when you want to change something in logic.

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java (hunk 5 above)
Comment (maexled) [reply src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]: You also forgot the `final`s

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java (hunk 7 above)
Comment (maexled) [reply src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]:
```suggestion
```

File: src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java (hunk 1 above)
Comment (delvh) [reply src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java]: `Max(100)`?

File: src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java (hunk 3 above)
Comment (delvh) [reply src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java]: Ah, I think I know why it doesn't:
That's a Hibernate "feature" if I remember that correctly: It uses `dynamic proxies` for objects it constructed meaning that any changes to the objects are immediately reflected in the database.
That's at least what I can remember, the last time I worked with Hibernate like that was about 4 years ago.

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java [hunk 8]
```diff
@@ -122,7 +125,10 @@ public PlayerTaskStatisticDTO submitData(final PlayerTaskStatisticData data) {
 
     logData(data, course, playerTaskStatistic, gainedKnowledge);
 
-    calculateCompletedDungeons(playerStatistic);
+    Area area = minigameTask.getArea();
+    if (area instanceof Dungeon) {
+      isDungeonCompleted((Dungeon) area, playerStatistic);
```
Comment (delvh) [inline src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]:
```suggestion
    if (area instanceof Dungeon dungeon) {
      isDungeonCompleted(dungeon, playerStatistic);
```

File: src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java (hunk 6 above)
Comment (delvh) [reply src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java]: 1. What's the reason for the duration?
2. Why in nano seconds?

File: src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java (hunk 4 above)
Comment (delvh) [reply src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java]: Is it? I'm not quite sure, the performance gain is probably marginal.
And it doesn't really make the code too much clearer…

File: src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java [hunk 9]
```diff
@@ -249,4 +249,94 @@ void submitGameData_MinigameDoesNotExist_ThrowNotFound() throws Exception {
...
+
+    MinigameTaskDTO updateMinigameTaskDTO = createdCourse
+      .getWorlds()
+      .get(0)
+      .getMinigameTasks()
+      .stream()
+      .findFirst()
+      .get();
+    System.out.println(updateMinigameTaskDTO.getIndex());
+    System.out.println(updateMinigameTaskDTO.getId());
```
Comment (delvh) [inline src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java]:
```suggestion
```

File: src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java [hunk 10]
```diff
@@ -249,4 +249,94 @@ void submitGameData_MinigameDoesNotExist_ThrowNotFound() throws Exception {
...
+      .andReturn();
+
+    final CourseDTO createdCourse = objectMapper.readValue(
+      resultCourse.getResponse().getContentAsString(),
+      CourseDTO.class
+    );
+
+    MinigameTaskDTO updateMinigameTaskDTO = createdCourse
+      .getWorlds()
+      .get(0)
```
Comment (delvh) [inline src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java]: Perhaps you should extract `createdCourse.getWorlds().get(0)` into a variable... you use it more than once.

File: src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java [hunk 11]
```diff
@@ -4,6 +4,7 @@
 import javax.validation.constraints.Max;
 import javax.validation.constraints.Min;
 import javax.validation.constraints.NotNull;
+import javax.validation.constraints.PositiveOrZero;
```
Comment (delvh) [inline src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatisticData.java]: Unused?

**Review by delvh — APPROVED** [review]

**Review by maexled — APPROVED** [review]
