### PR TITLE
Do not abort cloning when a minigame cannot be cloned

### LINKED ISSUE #273: Lecturer Interface: Do not abort clone when minigame configuration cannot be cloned
Additionally, report failed configuration clones to the user.

### PR DESCRIPTION
**Pull request by Aaron2000119**
Closes https://github.com/Gamify-IT/issues/issues/273.

To test use https://github.com/Gamify-IT/lecturer-interface/pull/37. 
Stop minigame backends and see if error toast messages appear.

### CODE REVIEW

File: src/main/java/de/unistuttgart/overworldbackend/data/MinigameTask.java [hunk 1]
```diff
@@ -24,38 +24,43 @@
...
 
-  public MinigameTask(final Minigame game, String description, final UUID configurationId, final int index) {
-    this.game = game;
-    this.configurationId = configurationId;
-    this.index = index;
-    this.description = description;
-  }
+    public MinigameTask(
+        final Minigame game,
+        @org.jetbrains.annotations.Nullable final String description,
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/data/MinigameTask.java]: can you fix the import?

File: src/main/java/de/unistuttgart/overworldbackend/data/NPC.java [hunk 2]
```diff
@@ -25,34 +24,34 @@
...
+        this.text = text;
+        this.index = index;
+    }
 
-  public NPC(final List<String> text, String description, final int index) {
-    this.text = text;
-    this.index = index;
-    this.description = description;
-  }
+    public NPC(final List<String> text, @org.jetbrains.annotations.Nullable final String description, final int index) {
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/data/NPC.java]: can you fix the import?

File: src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java [hunk 3]
```diff
@@ -16,328 +16,392 @@
...
+                    } catch (final FeignException e) {
+                        if (!errorMessages.contains("finitequiz-backend not present")) {
+                            errorMessages.add("bugfinder-backend not present");
+                        }
+                    }
+                }
+            default:
+                errorMessages.add(String.format("minigame %s doesn't exist", minigameTask.getGame()));
+                return new MinigameTask(Minigame.NONE, "", null, minigameTask.getIndex());
         }
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java]: way too long method.

File: src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java [hunk 4]
```diff
@@ -16,328 +16,392 @@
...
-    courseRepository.save(cloneCourse);
-    return courseMapper.courseToCourseDTO(cloneCourse);
-  }
+    public CourseCloneDTO cloneCourse(
+        final int id,
+        final CourseInitialData courseInitialData,
+        final String accessToken
+    ) {
+        errorMessages.clear();
+        currentAccessToken = accessToken;
```
Comment (maexled) [inline src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java]: setting the `currentAccessToken` as a class attribute is not the best thing to do...

**Review by maexled — APPROVED** [review]
Your choice if you want to fix the things I marked, depending on how much time you have left
